// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace KojackGames.Blackjack.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Paying Out")]
    public partial class PayingOutFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "014-PayingOut.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Paying Out", "In order to make money\r\nAs a Customer\r\nI should have winnings added to my pot whe" +
                    "n I win a game", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player gets Blackjack and beats Dealer")]
        public virtual void PlayerGetsBlackjackAndBeatsDealer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player gets Blackjack and beats Dealer", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 7
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table1);
#line 10
 testRunner.And("I have started a new game and bet \"10\"");
#line 11
 testRunner.And("I have \"10\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table2.AddRow(new string[] {
                        "Diamonds",
                        "Ace"});
            table2.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table2.AddRow(new string[] {
                        "Clubs",
                        "Ten"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Two"});
#line 12
 testRunner.And("the deck contains the following cards:", ((string)(null)), table2);
#line 18
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 19
 testRunner.When("I click on the deal button");
#line 20
 testRunner.Then("my pot should show \"$35.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Both player and dealer get blackjack so game ends in draw")]
        public virtual void BothPlayerAndDealerGetBlackjackSoGameEndsInDraw()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Both player and dealer get blackjack so game ends in draw", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table3.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 23
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table3);
#line 26
 testRunner.And("I have started a new game and bet \"5\"");
#line 27
 testRunner.And("I have \"10\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Ace"});
            table4.AddRow(new string[] {
                        "Spades",
                        "Ten"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table4.AddRow(new string[] {
                        "Clubs",
                        "Ace"});
#line 28
 testRunner.And("the deck contains the following cards:", ((string)(null)), table4);
#line 34
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 35
 testRunner.When("I click on the deal button");
#line 36
 testRunner.Then("my pot should show \"$15.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player loses")]
        public virtual void PlayerLoses()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player loses", ((string[])(null)));
#line 38
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table5.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 39
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table5);
#line 42
 testRunner.And("I have started a new game and bet \"5\"");
#line 43
 testRunner.And("I have \"10\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table6.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table6.AddRow(new string[] {
                        "Diamonds",
                        "Ace"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table6.AddRow(new string[] {
                        "Clubs",
                        "Ten"});
#line 44
 testRunner.And("the deck contains the following cards:", ((string)(null)), table6);
#line 50
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 51
 testRunner.When("I click on the deal button");
#line 52
 testRunner.Then("my pot should show \"$10.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player loses but has taken insurance")]
        public virtual void PlayerLosesButHasTakenInsurance()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player loses but has taken insurance", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table7.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 55
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table7);
#line 58
 testRunner.And("I have started a new game and bet \"5\"");
#line 59
 testRunner.And("I have \"10\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table8.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table8.AddRow(new string[] {
                        "Diamonds",
                        "Ace"});
            table8.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table8.AddRow(new string[] {
                        "Clubs",
                        "Ten"});
#line 60
 testRunner.And("the deck contains the following cards:", ((string)(null)), table8);
#line 66
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 67
 testRunner.And("I have \"10\" dollars in my pot");
#line 68
 testRunner.When("I click on the deal button");
#line 69
 testRunner.When("I click on take insurance");
#line 70
 testRunner.When("I stick");
#line 71
 testRunner.Then("my pot should show \"$15.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Double Down and win")]
        public virtual void DoubleDownAndWin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Double Down and win", ((string[])(null)));
#line 73
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table9.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 74
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table9);
#line 77
 testRunner.And("I have started a new game and bet \"10\"");
#line 78
 testRunner.And("I have \"30\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table10.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table10.AddRow(new string[] {
                        "Clubs",
                        "Two"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Three"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Jack"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "King"});
#line 79
 testRunner.And("the deck contains the following cards:", ((string)(null)), table10);
#line 88
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 89
 testRunner.When("I click on the deal button");
#line 90
 testRunner.When("I click on the double button");
#line 91
 testRunner.Then("my pot should show \"$70.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
